version: '3.8'
services:
  db:
    image: ankane/pgvector
    container_name: med_vector_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: medical_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: